Release 3.0
Significant reworking:

slackscan now perfoms the filter, blacklist and protect file processing
that was previously left to slackup. The result is that slacscan
now uses 'configuration profiles' instead of a config file.

slackup is now included in this distribution as it no longer makes
sense to ship it as a separate project given that so much of the
functionality is now in slackscan.

diff --git a/sbin/slackscan b/sbin/slackscan
--- a/sbin/slackscan
+++ b/sbin/slackscan
@@ -1,7 +1,7 @@
 #!/bin/bash -p
 #
 #  slackscan
-   version='2.12'
+   version='3.0'
 
 #  Copyright (c) 2013-2021, Gary Langshaw. <gary.langshaw@gmail.com>
 #  Permission to use, copy, modify, and/or distribute this software for any
@@ -16,56 +16,7 @@
 #  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 #  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-#  Description:
-#
-#    'slackscan' will scan a specified list of locations, either
-#    local, or remote, for available Slackware package files and
-#    compare the available packages to those currently installed.
-#
-#    The output of 'slackscan' may subsequently be used with other
-#    tools (such as the Slackware 'pkgtools' utilities) in order to
-#    syncronise the packages of the installed system with those
-#    available. 'slackscan' does not make any changes to the system
-#    itself.
-#
-#    Available packages are determined by searching for slackware
-#    package files (.t?z) in the locations specified contents of a
-#    config file.  The default config file location is:
-#    /etc/slackscan/default.conf.
-#    The user may specify an alternative config file by using the
-#    '-f' command-line option.
-#
-#    All specified locations must exist. A location may be one of:
-#
-#      o  A local directory containing slackware package files:
-#         which will be search recursively. The directory does not need
-#         to contain a CHECKSUMS.md5 file, or any other metadata.
-#         Existence of correctly named *.t?z package files is all that is
-#         required.
-#      o  A locally stored CHECKSUMS.md5 file:
-#         the relative paths of package files in the CHECKSUMS.md5 will
-#         be prefixed with the PATH to the CHECKSUMS.md5 file.
-#      o  A URL of a remote CHECKSUMS.md5 file:
-#         As above, but the CHECKSUMS.md5 will be fetched and all the
-#         package paths output will be prefixed with the URL path
-#         of the CHECKSUMS.md5 file.
-#
-#    In the event that multiple packages files are found that share
-#    the same base package name the first package file to be found is
-#    used for the comparison.
-#
-
-#  NOTES:
-#
-#    o  BLACKLISTING/FILTERING
-#       Blacklisting or selectively filtering of packages is considered
-#       out of scope for this utility and should be done by whatever
-#       tool acts on the generated lists. If you want these features
-#       checkout my 'slackup' utility, which is a front-end to
-#       'slackscan.'
-#
-
-set -e -o pipefail
+set -o pipefail
 
 unset IFS
 PATH='/usr/bin'
@@ -74,21 +25,23 @@ LC_ALL=C
 ########################################################################
 # check availability of external utilities:
 
-type mktemp find grep sed cut sort join uniq curl gpg >/dev/null || exit 1
+type mktemp find grep sed cut sort join uniq curl gpg >/dev/null \
+  || exit 1
 
 ########################################################################
 # Defaults:
 
-DEFAULT_CONFIG_FILE="/etc/slackscan/default.conf"
+SLACKSCAN_DIR='/etc/slackscan'
 
 ########################################################################
 # functions:
 
 function die()
 {
-  2>&1 printf "%s: %s\n" "${0##*/}" "${2:-aborted.}"
+  1>&2 printf "%s: %s\n" "${0##*/}" "${2:-aborted.}"
   exit ${1:-1}
 }
+
 remove_comments()
 {
   grep -v -E '^ *(#|$)' "${1:--}"
@@ -98,6 +51,100 @@ file_regex_type()
 {
   grep -q '^[[:space:]]*# Format: extended-regex' ${1:--} \
     &&  printf '-E'
+}
+
+function reformat_available()
+{
+   # format:  short-name long-name filename
+   sed -e 's|^\(.*/\)\([^/]\+\)-\([^-/]\+\)-\([^-/]\+\)-\([0-9]\+\)\([^-/]*\)\(\.t[^-/]z\)$|\2 \2-\3-\4-\5\6 \1\2-\3-\4-\5\6\7| ; t ; d '
+}
+
+function find_in_dir()
+{
+  if [ ! -d "$1" ]; then
+    die 1 "slackscan: directory not found, $1"
+  fi
+
+  find -L "$1" -type f -name "*.t?z" \
+    | reformat_available \
+    | sort -k 1,1
+
+  if [ $? -ne 0 ]; then
+    die 1 "error in find_in_dir()"
+  fi
+}
+
+function fetch_md5()
+{
+  local fd_sig
+
+  exec {fd_sig}<> "${workdir:-${TMPDIR:-/tmp}}/signature" || exit 1
+
+  if curl --retry 3 -s -f -o /dev/fd/$fd_checksums "$1" ; then
+    if [ ${o_skip_verify:-0} -ne 1 ]; then
+      curl --retry 3 -s -f -o /dev/fd/$fd_sig "$1.asc" \
+        && gpg --verify /dev/fd/$fd_sig /dev/fd/$fd_checksums >/dev/null 2>&1 \
+        || { die 16 "gpg --verify failed on $1" ; }
+    fi
+  else
+    die 16 "Aborted - could not fetch $1"
+  fi
+
+  exec {fd_sig}>&-
+}
+
+function reformat_md5()
+{
+  # extracts filepaths matching .t?z, prefixing with path to CHECKSUMS.md5
+  local prefix="${1%/}"
+  sed -e "s|\([[:alnum:]]\{32\}  \)\(\./\)\?\(.\+-[^-/]\+-[^-/]\+-[0-9]\+[^-/]*\.t[^-/]z\$\)|${prefix}/\3| ;t ;d"
+}
+
+function find_in_md5()
+{
+  local prefix=${1%/*}
+  local filename
+
+  exec {fd_checksums}<> "${workdir:-${TMPDIR:-/tmp}}/checksums" || exit 1
+
+  case "$1" in
+    http://*|https://*)  fetch_md5 "$1"
+                        filename=/dev/fd/$fd_checksums
+                        ;;
+
+    file://*|/* )  filename=${1#file://} ;;
+    *)  echo "unsupported: $1" ; exit 1 ;;
+  esac
+
+  if [ ! -r "$filename" ]; then
+    die 1 "slackscan: file not found, $filename"
+  fi
+
+  reformat_md5 "$prefix" < "$filename" \
+    | reformat_available \
+    | sort -k 1,1
+
+  exec {fd_checksums}>&-
+}
+
+function find_available()
+{
+  local pkg_source pkg_sources
+
+  mapfile -t pkg_sources < <( remove_comments "$conf" ) \
+    || die 1 "Could not read configuration file"
+
+  if [ ${#pkg_sources[@]} -eq 0 ]; then
+    die 1 "No package source locations found"
+  fi
+
+  for pkg_source in ${pkg_sources[@]}
+  do
+    case "$pkg_source" in
+      *.md5|*.MD5) find_in_md5 "$pkg_source" ;;
+                *) find_in_dir "$pkg_source" ;;
+    esac
+  done
 }
 
 function get_pkgdb_dir()
@@ -118,98 +165,6 @@ function reformat_installed()
    sed -e 's|^\(.*/\)\([^/]\+\)-\([^-/]\+\)-\([^-/]\+\)-\([0-9]\+\)\([^-]*\)$|\2 \2-\3-\4-\5\6| ; t ; d'
 }
 
-function reformat_available()
-{
-   # format:  short-name long-name filename
-   sed -e 's|^\(.*/\)\([^/]\+\)-\([^-/]\+\)-\([^-/]\+\)-\([0-9]\+\)\([^-/]*\)\(\.t[^-/]z\)$|\2 \2-\3-\4-\5\6 \1\2-\3-\4-\5\6\7| ; t ; d '
-}
-
-function find_in_dir()
-{
-  if [ ! -d "$1" ]; then
-    die 1 "slackscan: directory not found, $1"
-  fi
-
-  find -L "$1" -type f -name "*.t?z" \
-    | reformat_available \
-    | sort -k 1,1
-}
-
-function reformat_md5()
-{
-  # extracts filepaths matching .t?z, prefixing with path to CHECKSUMS.md5
-  local prefix="${1%/}"
-  sed -e "s|\([[:alnum:]]\{32\}  \)\(\./\)\?\(.\+-[^-/]\+-[^-/]\+-[0-9]\+[^-/]*\.t[^-/]z\$\)|${prefix}/\3| ;t ;d"
-}
-
-function fetch_md5()
-{
-  local signature
-
-  exec {signature}<> "${workdir:-${TMPDIR:-/tmp}}/signature" || exit 1
-
-  if curl --retry 3 -s -f -o /dev/fd/$checksums "$1" ; then
-    if [ ${o_skip_verify:-0} -ne 1 ]; then
-      curl --retry 3 -s -f -o /dev/fd/$signature "$1.asc" \
-        && gpg --verify /dev/fd/$signature /dev/fd/$checksums >/dev/null 2>&1 \
-        || { die 16 "gpg --verify failed on $1" ; }
-    fi
-  else
-    die 16 "Aborted - could not fetch $1"
-  fi
-
-  exec {signature}>&-
-}
-
-function find_in_md5()
-{
-  local prefix=${1%/*}
-  local filename
-
-  exec {checksums}<> "${workdir:-${TMPDIR:-/tmp}}/checksums" || exit 1
-
-  case "$1" in
-    http://*|https://*)  fetch_md5 "$1"
-                        filename=/dev/fd/$checksums
-                        ;;
-
-    file://*|/* )  filename=${1#file://} ;;
-    *)  echo "unsupported: $1" ; exit 1 ;;
-  esac
-
-  if [ ! -r "$filename" ]; then
-    die 1 "slackscan: file not found, $filename"
-  fi
-
-  reformat_md5 "$prefix" < "$filename" \
-    | reformat_available \
-    | sort -k 1,1
-
-  exec {checksums}>&-
-}
-
-function find_available()
-{
-  local pkg_source pkg_sources
-
-  mapfile -t pkg_sources < <( remove_comments "$conf" ) \
-    || die 1 "Could not read configuration file"
-
-  for pkg_source in ${pkg_sources[@]}
-  do
-    case "$pkg_source" in
-      *.md5|*.MD5) find_in_md5 "$pkg_source" ;;
-                *) find_in_dir "$pkg_source" ;;
-    esac
-  done
-}
-
-function list_available()
-{
-  find_available \
-    | sort -u -k 1,1
-}
-
 function list_installed()
 {
   local pkgdatadir=$( get_pkgdb_dir )
@@ -217,47 +172,118 @@ function list_installed()
   find -H "$pkgdatadir" -type f \
     | reformat_installed \
     | sort -k 1,1
+
+  if [ $? -ne 0 ]; then
+    die 1 "error in list_installed()"
+  fi
+}
+
+function run_file_filter()
+{
+  local infile=$1 grep_opt=$2
+  local fd_temp1 filter_cmd
+  local count regex_type
+
+  if [ -e "$infile" ]; then
+    regex_type=$( file_regex_type "$infile")
+    exec {fd_temp1}<> "$( mktemp -p "$workdir" temp1.XXXXXX )"
+    remove_comments "$infile" >&$fd_temp1
+    count=$( wc -l </dev/fd/$fd_temp1 )
+  fi
+
+  if [ ${count:-0} -gt 0 ]; then
+    filter_cmd="grep $grep_opt $regex_type -f /dev/fd/$fd_temp1"
+  else
+    filter_cmd='cat'
+  fi
+
+  $filter_cmd
+
+  [ -n "$fd_temp1" ] && exec {fd_temp1}>&-
+}
+
+function apply_filter()
+{
+  if [ ${o_ignore_filter:-0} -eq 1 ]; then
+    cat
+  else
+    run_file_filter "$filter_file"
+  fi
+}
+
+function apply_blacklist()
+{
+  if [ ${o_ignore_blacklist:-0} -eq 1 ]; then
+    cat
+  else
+    run_file_filter "$blacklist_file" -v
+  fi
+}
+
+function list_available_filtered()
+{
+  find_available \
+    | apply_filter \
+    | apply_blacklist \
+    | sort -u -k 1,1
+
+  if [ $? -ne 0 ]; then
+    die 1 "error in list_available_filtered()"
+  fi
+}
+
+function apply_protect()
+{
+  if [ ${o_ignore_protect:-0} -eq 1 ]; then
+    cat
+  else
+    run_file_filter "$protect_file" -v
+  fi
 }
 
 function create_table
 {
-  local dups available installed
+  local dups fd_available fd_installed
 
-  exec {available}<> "${workdir:-${TNPDIR:-/tmp}}/available"  || exit 1
-  exec {installed}<> "${workdir:-${TMPDIR:-/tmp}}//installed" || exit 1
+  exec {fd_available}<> "${workdir:-${TNPDIR:-/tmp}}/available"  || exit 1
+  exec {fd_installed}<> "${workdir:-${TMPDIR:-/tmp}}/installed"  || exit 1
 
-  list_available >&$available
+  list_available_filtered >&$fd_available
 
-  list_installed >&$installed \
+  list_installed >&$fd_installed \
     || die 1 "Could not query list of installed packages"
 
   #  Duplicates can lead to incorrect output, so abort.
-  dups=$( wc -l < <( uniq -d <( cut -f1 -d ' ' /dev/fd/$installed) ) )
+  dups=$( wc -l < <( uniq -d <( cut -f1 -d ' ' /dev/fd/$fd_installed) ) )
   if [ ${dups:-0} -gt 0 ]; then
     die 1 "Aborted - multiple packages installed with the same base package name."
   fi
 
-  sort -u -k 1,1 <( cut -f1 -d ' ' /dev/fd/$installed ) \
-                 <( cut -f1 -d ' ' /dev/fd/$available ) \
-    | join -a 1 -e 'not-installed' -o 1.1,2.2 - /dev/fd/$installed \
-    | join -a 1 -e 'not-available' -o 1.1,1.2,2.2,2.3 - /dev/fd/$available
+  sort -u -k 1,1 <( cut -f1 -d ' ' /dev/fd/$fd_installed ) \
+                 <( cut -f1 -d ' ' /dev/fd/$fd_available ) \
+    | join -a 1 -e 'not-installed' -o 1.1,2.2 - /dev/fd/$fd_installed \
+    | join -a 1 -e 'not-available' -o 1.1,1.2,2.2,2.3 - /dev/fd/$fd_available
 
-  exec {available}>&-
-  exec {installed}>&-
+  if [ $? -ne 0 ]; then
+    die 1 "error in create_table()"
+  fi
+
+  exec {fd_available}>&-
+  exec {fd_installed}>&-
 }
 
 function report()
 {
   local package installed available pkgpath
-  local report_i report_U report_r
+  local fd_rep_i fd_rep_u fd_rep_r
 
   [ "$o_install" = "-" ] && o_install=/dev/fd/1
   [ "$o_upgrade" = "-" ] && o_upgrade=/dev/fd/1
   [ "$o_remove" = "-" ]  && o_remove=/dev/fd/1
 
-  [ ! -z "$o_install" ] && { exec {report_i}<> "$o_install" || exit 1 ; }
-  [ ! -z "$o_upgrade" ] && { exec {report_u}<> "$o_upgrade" || exit 1 ; }
-  [ ! -z "$o_remove" ]  && { exec {report_r}<> "$o_remove"  || exit 1 ; }
+  [ ! -z "$o_install" ] && { exec {fd_rep_i}<> "$o_install" || exit 1 ; }
+  [ ! -z "$o_upgrade" ] && { exec {fd_rep_u}<> "$o_upgrade" || exit 1 ; }
+  [ ! -z "$o_remove" ]  && { exec {fd_rep_r}<> "$o_remove"  || exit 1 ; }
 
   while read package installed available pkgpath
   do
@@ -265,63 +291,61 @@ function report()
       -a "$installed" != 'not-installed' \
       -a "$available" != 'not-available' \
       -a "$available" != "$installed" ]; then
-      echo "$pkgpath" >&$report_u
+      echo "$pkgpath" >&$fd_rep_u
     fi
     if [ "$o_install" \
       -a "$installed" == 'not-installed' ]; then
-      echo "$pkgpath" >&$report_i
+      echo "$pkgpath" >&$fd_rep_i
     fi
     if [ "$o_remove" \
       -a "$installed" != 'not-installed' \
       -a "$available" == 'not-available' ]; then
-      echo "$installed" >&$report_r
+      echo "$installed" >&$fd_rep_r
     fi
   done
 
-  [ -n "$report_i" ]  &&  exec {report_i}>&-
-  [ -n "$report_u" ]  &&  exec {report_u}>&-
-  [ -n "$report_r" ]  &&  exec {report_r}>&-
+  [ -n "$fd_rep_i" ]  &&  exec {fd_rep_i}>&-
+  [ -n "$fd_rep_u" ]  &&  exec {fd_rep_u}>&-
+  [ -n "$fd_rep_r" ]  &&  exec {fd_rep_r}>&-
 }
 
 ########################################################################
 # parse arguments
 
-unset o_install o_remove o_upgrade o_config o_profile o_usage o_skip_verify
+unset o_install o_remove o_upgrade \
+      o_ignore_blacklist o_ignore_filter o_ignore_protect \
+      o_config o_profile o_usage o_skip_verify
 
 if [ $# -eq 0 ]; then
    o_usage=1
 fi
 
-while getopts ':f:p:i:u:r:hN' opt
+while getopts ':p:i:u:r:hBFNP' opt
 do
   case "$opt" in
-    f)  o_config=$OPTARG   ;;
-    p)  o_profile=$OPTARG  ;;
-    h)  o_usage=1          ;;
-    i)  o_install=$OPTARG  ;;
-    r)  o_remove=$OPTARG   ;;
-    u)  o_upgrade=$OPTARG  ;;
-    N)  o_skip_verify=1    ;;
+    p)  o_profile=$OPTARG       ;;
+    h)  o_usage=1               ;;
+    i)  o_install=$OPTARG       ;;
+    r)  o_remove=$OPTARG        ;;
+    u)  o_upgrade=$OPTARG       ;;
+    B)  o_ignore_blacklist=1    ;;
+    F)  o_ignore_filter=1       ;;
+    P)  o_ignore_protect=1      ;;
+    N)  o_skip_verify=1         ;;
     \?) die 1 "Unexpected option: -$OPTARG" ;;
     :)  die 1 "Missing operand for option -$OPTARG" ;;
   esac
 done
 shift $(( OPTIND - 1 ))
 
-
-if [ -n "$o_config" ]; then
-  case "$o_config" in
-    - ) conf=/dev/stdin  ;;
-    *)  conf=$o_config   ;;
-  esac
-elif [ -n "$o_profile" ] || [ -n "$SLACKUP_PROFILE" ]; then
-  conf="/etc/slackup/${o_profile:-${SLACKUP_PROFILE}}/scan"
-  filter="/etc/slackup/${o_profile:-${SLACKUP_PROFILE}}/filter"
-  blacklist="/etc/slackup/${o_profile:-${SLACKUP_PROFILE}}/blacklist"
-  protect="/etc/slackup/${o_profile:-${SLACKUP_PROFILE}}/protect"
-else
-  conf=$DEFAULT_CONFIG_FILE
+if [ -z "$o_profile" ]; then
+  o_profile="${SLACKSCAN_PROFILE:-default}"
 fi
+
+conf="${SLACKSCAN_DIR%/}/${o_profile}/scan"
+filter_file="${SLACKSCAN_DIR%/}/${o_profile}/filter"
+blacklist_file="${SLACKSCAN_DIR%/}/${o_profile}/blacklist"
+protect_file="${SLACKSCAN_DIR%/}/${o_profile}/protect"
 
 ########################################################################
 
@@ -333,34 +357,34 @@ fi
 if [ "$o_usage" ]; then
   printf '%s\n' \
     'Usage:' \
-    '         slackscan [ -N ] [ [ -f filename ] | [ -p profile ] ] ' \
-    '                   [-i filename ] [ -u filename ] [ -r filename ] ' \
+    '  slackscan [ -NBFP ] [ [ -p profile ]' \
+    '            [-i filename ] [ -u filename ] [ -r filename ] ' \
     '' \
-    '           where, ' \
-    '             -f :   specifies the filename of the config file' \
-    '             -p :   specifies 'slackup' profile name as alternative way to' \
-    '                    select a config file' \
-    '             -i :   specifies file to hold list of packages to be installed. ' \
-    '             -u :   specifies file to hold list of packages to be upgraded. ' \
-    '             -r :   specifies file to hold list of packages to be removed. ' \
-    "             -N :   skip 'gpg --verify' of downloaded CHECKSUMS.md5 files. " \
-    "                    (INSECURE). " \
+    '  where, ' \
+    '    -p :   specifies profile name.' \
+    '    -i :   specifies file to hold list of packages to be installed. ' \
+    '    -u :   specifies file to hold list of packages to be upgraded. ' \
+    '    -r :   specifies file to hold list of packages to be removed. ' \
+    "    -N :   skip 'gpg --verify' of downloaded CHECKSUMS.md5 files. " \
+    "           (INSECURE). " \
+    "    -B :   ignore the blacklist file." \
+    "    -F :   ignore the filter file." \
+    "    -P :   ignore the protect file." \
     ''
-   printf 'Configured package locations in %s:\n' "$conf"
-   printf '  %s\n' "${pkg_sources[@]}"
    exit 0
 fi
 
 ########################################################################
 
 workdir="$( mktemp -d /tmp/slackscan.XXXXXX )" \
-  && cd "$workdir" || exit 1
+  && cd "$workdir" || exit 16
 
-exec {table}<> "$workdir/table"  ||  exit 1
+exec {table}<> "$workdir/table"  \
+  || die 1 "Could not create table file"
 
 create_table >&$table
 
-report < /dev/fd/$table
+report < /dev/fd/$table | apply_protect
 
 exec {table}>&-
 
