search for available gpg verify utilities
Slackware 15.1 will be changing the default implementation of
gnupg from gnupg v1 to gnupg v2. This change has already been made
in slackware-current.

'gpg v2' has a larger set of runtime dependencies than gpg v1, so
in order to reduce the amount of runtime dependencies and hopefully
improve robustness during system updates the following changes have
been made...

  slackscan/slackup:

    search for the gpg verification tool to use in the following
    order of precidence:  gpgv1 gpgv gpgv2 gpg1 gpg gpg2

  slackscan_update_generator:

    use 'gpgv'

diff --git a/sbin/slackscan b/sbin/slackscan
--- a/sbin/slackscan
+++ b/sbin/slackscan
@@ -86,8 +86,8 @@ function fetch_md5()
   if curl --retry 3 -s -f -o /dev/fd/$fd_checksums "$1" ; then
     if [ ${o_skip_verify:-0} -ne 1 ]; then
       curl --retry 3 -s -f -o /dev/fd/$fd_sig "$1.asc" \
-        && gpg --verify /dev/fd/$fd_sig /dev/fd/$fd_checksums >/dev/null 2>&1 \
-        || { die 8 "gpg --verify failed on $1" ; }
+        && $gpg_verify_cmd /dev/fd/$fd_sig /dev/fd/$fd_checksums >/dev/null 2>&1 \
+        || { die 8 "gpg verification failed on $1" ; }
     fi
   else
     die 16 "Aborted - could not fetch $1"
@@ -335,12 +335,6 @@ function print_stats()
 }
 
 ########################################################################
-# check availability of external utilities:
-
-type mktemp find grep sed cut sort join uniq curl gpg >/dev/null \
-  || die 16 "external utilties not found"
-
-########################################################################
 # parse arguments
 
 unset o_install o_remove o_upgrade \
@@ -390,7 +384,7 @@ if [ "$o_usage" ]; then
     '    -i :   specifies file to hold list of packages to be installed. ' \
     '    -u :   specifies file to hold list of packages to be upgraded. ' \
     '    -r :   specifies file to hold list of packages to be removed. ' \
-    "    -N :   skip 'gpg --verify' of downloaded CHECKSUMS.md5 files. " \
+    "    -N :   skip gpg verify of downloaded CHECKSUMS.md5 files. " \
     '           (INSECURE). ' \
     '    -B :   ignore the blacklist file.' \
     '    -F :   ignore the filter file.' \
@@ -399,6 +393,28 @@ if [ "$o_usage" ]; then
     '    -P :   ignore the protect file.' \
     ''
    exit 0
+fi
+
+########################################################################
+# check availability of external utilities:
+
+type mktemp find grep sed cut sort join uniq curl >/dev/null \
+  || die 16 "external utilties not found"
+
+unset gpg_verify_cmd
+
+if [ "${o_skip_verify:-0}" -eq 0 ]; then
+  for file in gpgv1 gpgv gpgv2 gpg1 gpg gpg2 ""
+  do
+    gpg=$(type -p "$file") && break
+  done
+
+  case "$gpg" in
+    */gpgv* )  gpg_verify_cmd="$gpg --keyring pubring.gpg" ;;
+    */gpg*  )  gpg_verify_cmd="$gpg --verify" ;;
+    *       )  die 16 "Could not find gpg command" ;;
+  esac
+  unset gpg file
 fi
 
 ########################################################################
diff --git a/sbin/slackup b/sbin/slackup
--- a/sbin/slackup
+++ b/sbin/slackup
@@ -55,13 +55,6 @@ cleanup()
 }
 
 ########################################################################
-# check availability of external utilities:
-
-if ! type mktemp xargs gpg grep sed >/dev/null ; then
-  die 1 "external dependencies missing."
-fi
-
-########################################################################
 # Parse options:
 
 unset o_usage o_verify_pkg_sig
@@ -122,10 +115,10 @@ show_usage()
     '        -x    execute generated commands instead of writing them to stdout. ' \
     '        -c    add comment lines to output to be more readable.' \
     '        -i    include invocation of post-install scripts. ' \
-    '        -s    include gpg --verify of package files. ' \
+    '        -s    include gpg verify of package files. ' \
     '        -h    show usage text.' \
     '        -E    interpret PATTERN as extended-regex.' \
-    '        -N    do not gpg --verify CHECKSUMS.md5 files.' \
+    '        -N    do not gpg verify CHECKSUMS.md5 files.' \
     '        -I    ignore new packages.' \
     '        -U    ignore updated packages.' \
     '        -R    ignore removed packages.' \
@@ -143,6 +136,31 @@ fi
 if [ ${o_execute:-0} -eq 1 ] && [ ${o_list_only:-0} -eq 1 ]; then
   die 1 "-l and -x are mutually exclusive."
 fi
+
+########################################################################
+# check availability of external utilities:
+
+if ! type mktemp xargs grep sed >/dev/null ; then
+  die 1 "external dependencies missing."
+fi
+
+unset gpg_verify_cmd
+
+for file in gpgv1 gpgv gpgv2 gpg1 gpg gpg2 ""
+do
+  gpg=$(type -p "$file") && break
+done
+
+case "$gpg" in
+  */gpgv* )  gpg_verify_cmd="$gpg --keyring pubring.gpg" ;;
+  */gpg*  )  gpg_verify_cmd="$gpg --verify" ;;
+  *       )  if [ "${o_verify_checksums:-1}" -eq 1 ] \
+                [ "${o_verify_pkg_sig:-0}" -eq 1 ] ; then
+                die 16 "Could not find gpg command"
+             fi
+             ;;
+esac
+unset gpg file
 
 ########################################################################
 # temporary workdir/files:
@@ -242,8 +260,8 @@ gen_up()
         ;;
     esac
     if [ ${o_verify_pkg_sig:-0} -eq 1 ]; then
-      printf 'gpg --verify \\\n  %s \\\n  %s \\\n&&  ' \
-        "$pkgfile.asc" "$pkgfile"
+      printf '%s \\\n  %s \\\n  %s \\\n&&  ' \
+        "$gpg_verify_cmd" "$pkgfile.asc" "$pkgfile"
     fi
     printf 'upgradepkg %s %s' "$pkg_opt" "$pkgfile"
     if [ ${o_post_install:-0} -eq 1 ]; then
